pipeline {
  agent any
  tools {
    maven "M3"
    jdk"JDK11"
  }
  environment {
        AWS_CREDENTIAL_NAME = "AWSCredentials"
        REGION = "ap-northeast-2"
        ECR_REPOSITORY = "${params.AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com"
        ECR_DOCKER_IMAGE = "${ECR_REPOSITORY}/${params.DOCKER_IMAGE_NAME}"
        ECR_DOCKER_TAG = "${DOCKER_TAG}"
  }
  
  stages {
    stage('Git fatch') {
      steps {
        echo 'Git fatch'
        git url: 'https://github.com/RB1123/spring-petclinic.git/',
          branch: 'main', credentialsId: 'gitCredential'
      }
    }
    stage('maven Build') {
      steps {
        echo 'maven Build'
        sh 'mvn -Dmaven.test.failure.ignore=true clean package'
      }
    }
    stage('Docker Image') {
      steps {
        echo 'Docker Image'
        dir("${env.WORKSPACE}") {
          sh 'docker build -t aws00-spring-petclinic:1.0 .'
        }
      }
    }
    stage('Image Push') {
      steps {
        echo 'Image Push'
      }
    }
    stage('Codedeploy Workload') {
      steps {
        echo 'codedeploy Workload'
      }
    }
  }
}
