pipeline {
  agent any
  tools {
    maven "M3"
    jdk"JDK11"
  }
  
  stages {
    stage('Git fatch') {
      steps {
        echo 'Git fatch'
        git url: 'https://github.com/RB1123/spring-petclinic.git/',
          branch: 'main', credentialsId: 'gitCredential'
      }
    }
    stage('maven Build') {
      steps {
        echo 'maven Build'
        sh 'mvn -Dmaven.test.failure.ignore=true clean package'
      }
    }
    stage('Docker Image') {
      steps {
        echo 'Docker Image'
      }
    }
    stage('Image Push') {
      steps {
        echo 'Image Push'
      }
    }
    stage('Codedeploy Workload') {
      steps {
        echo 'codedeploy Workload'
      }
    }
  }
}
